### ISSUE TITLE
How to bundle assets to a label.zip

### ISSUE THREAD

**Issue by aron19951209** [semantic-release/gitlab#111]
Is it possible to keep folder structure and bundle to a zip like following:
```
"@semantic-release/gitlab",
{
    "assets": [
        { paths: ["dist/**/*"], label: "dist.zip" }
    ]
}
```

**Comment by pvdlg** [comment]
You would have to do that as part of your build, after generating the assets you want to bundle.
The scope of this plugin is to upload assets to a GitLab release. Producing those file is the responsibility of your project build scripts. It wouldn't make much sense to move the bundling to this plugin anyway as every project bundle differently.

**Comment by aron19951209** [comment]
@pvdlg This's what I expected:
![bootstrap github](https://i.imgur.com/RgDwxvW.png)

The plugin @semantic-release/git can meet the needs of the above picture, I hope this plugin so.

**Comment by jeff-cook** [comment]
https://gitlab.com/alelec/gitlab-release does this, but I think they just take the list of artifacts and create a zip file on the fly. You could do this before you run semantic-release or take a look at https://github.com/semantic-release/exec as a possible way to include it in `semantic-release`.
