### ISSUE TITLE
Understanding inconsistent behavior across github, gitlab, and git plugins

### ISSUE THREAD

**Issue by amclin** [semantic-release/gitlab#113]
It's a bit strange that @semantic-release/gitlab will tag a commit and create a gitlab release, but it doesn't do the other features that @semantic-release/git will do, such as committing changed files with a specified commit message.

If I remember correctly, @semantic-release/github creates a github release, but does NOT tag a commit. You are relegated to using the git plugin for tagging.

Since tagging is part of the contents of the git repo, and not a property of the repository hosting, shouldn't the behavior be consistent? If making changes to the git repo is part of the repository hosting process, then shouldn't all the features of git be supported (or encapsulated) in the repo hosting plugin as well?

**Comment by travi** [comment]
tagging is part of semantic-release core, not the git plugin. semantic-release needs the version tags to be present in the commit history to determine when the previous version was released when determining the details of the next release, so it must be in core.

what evidence are you seeing of tagging happening outside of core?

**Comment by amclin** [comment]
If my project uses the gitlab plugin, without the git plugin, then a tag is still created, presumably via the gitlab API?

It's confusing that a git operation (tagging) works, but other git operations do not work because the plugin is not present.

Furthermore, since URL configurations and requirements differ between plugins, it caused me a lot of confusion in getting things working on corporate network with messy proxy requirements: (is the tag pushed over the Gitlab API or is it via `git push`? Because if it's `git push`, then it doesn't seem to be using the same git remote URL and auth as the git plugin does by default, and not the one provided in .git remotes used for the original clone.

I apologize if this is confusing, it's a lot of me thinking out loud as I try to figure out what is going on under the hood between the plugins now that I finally have a working setup behind my corporate proxies and authentication requirements after many days of trial and error.

**Comment by travi** [comment]
tags are pushed using git, not the api of the hosting provider. core does not know anything about the hosting providers, so couldn't use the appropriate api for each setup anyway.

i'm personally less familiar with the gitlab plugin, but the github plugin uses the api to associate release notes with the tag that was pushed.

you mention other git operations not working without the git plugin. what other git operations are you attempting? are they failing? providing output from failures would be helpful in better understanding the problems you are seeing.

**Comment by pvdlg** [comment]
As explained by @travi:
- `semantic-release`core: push tags (and add Git notes in v16) to remote with `git` CLI, authenticating with https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#push-access-to-the-remote-repository
- `@semantic-release/github`: Interact with GitHub API to create releases, comment on issues etc... authenticated with `GITHUB_TOKEN`/`GH_TOKEN`
- `@semantic-release/gitlab`: Interact with GitLab API to create releases etc... authenticated with `GITLAB_TOKEN`/`GL_TOKEN`
- `@semantic-release/git`: Interact with the remote Git repo (any type of Git repo) to commit files with `git` CLI, authenticating with https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#push-access-to-the-remote-repository

As you can see, the scope of `@semantic-release/github` and `@semantic-release/gitlab` are consistent. They both deal with things that require the respective API.
