### ISSUE TITLE
Automatically populate gitlabUrl when running from gitlab pipelines

### ISSUE THREAD

**Issue by amclin** [semantic-release/gitlab#114]
When using gitlab pipelines, it would be nice to populate `gitlabUrl` and `gitlabApiPathPrefix` automatically, as the necessary values are provided by the pipelines:

Gitlab pipelines provide the following environment variables out of the box:

- `CI_API_V4_URL` is directly the api url, replacing `GITLAB_URL` **and** `GITLAB_PREFIX`
- `CI_SERVER_HOST` is the GitLab hostname, replacing `GITLAB_URL`

```bash
$ echo ${GITLAB_URL}
https://gitlab.local/

$ echo ${CI_API_V4_URL}
https://gitlab.local/api/v4

$ echo ${CI_SERVER_HOST}
gitlab.local
```

It is a shame to be oblige to declare the GitLab url into a GitLab CI pipeline. GitLab knows about its own url.

_Originally posted by @oupala in https://github.com/semantic-release/gitlab/issues/105#issuecomment-566558092_

**Comment by amclin** [comment]
Workaround is specifying them on the command (and setting the prefix to an empty string)
`GITLAB_URL=$CI_API_V4_URL GITLAB_PREFIX="" semantic-release`

But it would be much nicer to have that automatically

**Comment by oupala** [comment]
It works well, thanks!
