### ISSUE TITLE
"Validation failed: Description can't be blank"

### ISSUE THREAD

**Issue by TSilviu** [semantic-release/gitlab#125]
Getting `Response code 400 (Bad Request)` when trying to publish release assets to GitLab.

This is the body of the request: `body: '{"tag_name":"v5.5.0","description":""}'` and this is the URL we are posting to: `'https://lab.arachnys.com/api/v4/projects/arachnys%2Farachnys-ui/repository/tags/v5.5.0/release'` . 
It looks like the `description` field of the body is blank, which is what is causing this problem, although I can't find any way to set a description message in your README.

Despite getting this error, the release tag is still updated on Gitlab, but with no assets.

This is the config in our `.releaserc`:
```
        ["@semantic-release/gitlab", {
            "assets": [
                {
                    "path": [
                        "package.json",
                        "dist/**/*.js",
                        "dist/**/*.d.ts",
                    ],
                    "label": "JS and TS declaration files"
                }
            ]
        }]
```

Let me know if you have any questions and I can provide more details. Thanks!

**Comment by pvdlg** [comment]
What we send in the `description` is what's produced by the generate changelog plugin. It seems you don't use any plugin to generate the changelog (the default is https://github.com/semantic-release/release-notes-generator).

That said, we should handle that case more gracefully.
