### ISSUE TITLE
Order of release assets is scrambled

### ISSUE THREAD

**Issue by tommyalatalo** [semantic-release/gitlab#132]
I just started using this plugin to create gitlab releases, but I see that the assets on the release page are in a scrambled order?

My plugin is set up like this:
```
    ["@semantic-release/gitlab", {
      "assets": [
        {"path": "CHANGELOG.md", "label": "Changelog"},
        ['dist/*.tar.gz','dist/*.zip', "dist/*SHA256SUMS"],
      ]
    }],
```

The order of the assets on the release however end up something like this:
```
myrelease_1.0.0_darwin_x86_64.tar.gz
myrelease_1.0.0_linux_arm64.tar.gz
myrelease_1.0.0_linux_i386.tar.gz
myrelease_1.0.0_linux_x86_64.tar.gz
myrelease_1.0.0_SHA256SUMS
Changelog
myrelease_1.0.0_windows_i386.zip
myrelease_1.0.0_windows_x86_64.zip
```

Is there a way to define the order that the assets land on the release page?
I would understand if the globbed assets are in random order, but why is the changelog randomly in the middle there?

**Comment by pvdlg** [comment]
The assets are uploaded and added to the release with multiple API calls executed in parallel. The final order is unpredictable and will depend on file size, network traffic, etc...

So there is no way to configure the order of the assets added to the release.
