### ISSUE TITLE
Upcoming release config

### ISSUE THREAD

**Issue by yyynnn** [semantic-release/gitlab#136]
Add ability to pass upcoming release state via `releasedAt/upcoming` config option:

```
{
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    ["@semantic-release/gitlab", {
      "gitlabUrl": "https://custom.gitlab.com",
      "releasedAt": "SOME_TIMESTAMP_OR_ENV_VAR", // or "upcoming": true
      "assets": [
        {"path": "dist/asset.min.css", "label": "CSS distribution"},
        {"path": "dist/asset.min.js", "label": "JS distribution"}
      ]
    }],
  ]
}
```

**Comment by yyynnn** [comment]
Its king of strange that i cannot switch this in gitlab ui  to make pre/alpha/beta-release

**Comment by pvdlg** [comment]
What would those options? Can you add details and context to your request?

**Comment by yyynnn** [comment]
@pvdlg i need to make a pre/alpha/beta release to test things out (to see changelogs, version bumps ) before making an actual stable release

**Comment by pvdlg** [comment]
You can use the `--dry-run` option locally to see in the console the next version and changelog.

**Comment by yyynnn** [comment]
i know
yeah this is just a problem of a gitlab's shitty ui
