### ISSUE TITLE
Commit files with updated version number with tag

### ISSUE THREAD

**Issue by alexives** [semantic-release/gitlab#143]
In many cases, a hard coded version number is included in the code that needs to be updated when a new version is released. It would be nice if we could optionally create a commit with those files in it and tag that, instead of tagging the current commit.

Gitlab's api supports this - https://docs.gitlab.com/ee/api/commits.html

**Comment by alexives** [comment]
Actually, I'm sorry this doesn't need to happen I just realized there are better ways.

**Comment by jeff-cook** [comment]
@alexives what did you come up with? I'm kind of looking for the same thing.

**Comment by alexives** [comment]
I honestly have no recollection of what I did.... and I'm not sure what project I was using this on.
