### ISSUE TITLE
Any way to use SSH key instead of GL_TOKEN/GITLAB_TOKEN?

### ISSUE THREAD

**Issue by isuftin** [semantic-release/gitlab#150]
We do not use personal access tokens across projects for write access. We do use SSH keys that we can set up per-project in GitLab.

Based on this comment: https://github.com/semantic-release/gitlab/issues/64#issuecomment-460440848 - I was assuming that we could use an SSH key to drive this plugin but it doesn't seem like that's the case?

Is there any combination of variables I can set in GitLab or settings for this plugin to have this plugin drive via an SSH key (that's already added to ssh-agent during the run)?

**Comment by isuftin** [comment]
It doesn't seem like this is a thing

**Comment by jeff-cook** [comment]
I don't see a way to use an SSH key to access the GitLab API. This would be required to create the release. If all you need is the tag created, you can do that with an SSH key and don't need the `semantic-release/gitlab` plugin.
