### ISSUE TITLE
Support Links

### ISSUE THREAD

**Issue by vegaed** [semantic-release/gitlab#154]
Would like the ability to add links to the release. https://docs.gitlab.com/ee/user/project/releases/#links. Want to link to the produced docker image in the container registry.

**Comment by jeremypetit-grtgaz** [comment]
I'm also interested in that feature for docker images and other packages (maven,npm...)

**Comment by jeff-cook** [comment]
I think what you are looking for is assets in the configuration. https://github.com/semantic-release/gitlab#usage

**Comment by vegaed** [comment]
@jeff-cook I really dont want to have to export my docker images to have it included in the release. Also docker images can be quite large. Hence why I just want a link, which gitlab supports.

**Comment by jeff-cook** [comment]
I see. In reality all the assets in the release are just links. 

Would need to add an `assets:url` option and not upload the file. 

Possible work around: You could add to the description for the release. Not sure if that would be in the `gitlab` plugin or a different plugin.

**Comment by lukasmrtvy** [comment]
I would like to see a full API support https://docs.gitlab.com/ee/api/releases/#create-a-release

My use case ( example pipeline ):
- create jar
- upload jar to external maven repository ( not to Gitlab )
- create docker image
- upload image to external docker registry ( not to Gitlab )
- create release ( create links with proper links:type atribute )

So whole POST looks like:
```
curl --header 'Content-Type: application/json' --header "PRIVATE-TOKEN: <your_access_token>" \
     --data '{ "name": "New release", "tag_name": "v0.3", "description": "Super nice release. Additional info generated by pipeline: \"$FOOTER_DESCRIPTION\"", "assets": { "links": [{ "name": "foo", "url": "https://maven-repository/foo.jar", "link_type":"package" },{ "name": "bar", "url": "https://docker-registry/bar", "link_type":"image" }] } }' \
     --request POST "https://gitlab.example.com/api/v4/projects/24/releases"
```

Also something like `$FOOTER_DESCRIPTION` to add additional info to release description would be great.


Related: https://github.com/semantic-release/gitlab/issues/161
Related: https://github.com/semantic-release/gitlab/issues/167
