### ISSUE TITLE
Can't make it work with Project Access Tokens or Deploy Tokens

### ISSUE THREAD

**Issue by Oloremo** [semantic-release/gitlab#163]
Seems to be working fine with Personal User Tokens but it's suboptimal on paid licenses.

It should work just fine with Project Access Tokens: https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html
Or with Project Deploy Tokens: https://docs.gitlab.com/ee/user/project/deploy_tokens/

But I can't make it work:
```
"fatal: Authentication failed for 'https://gitlab-ci-token:[secure]@gitlab.mydomain.com/path/to/repo.git/'",
```

Any guidance?

**Comment by Park0** [comment]
I have the same issue. It worked for me on one repo but it does not work on another. But as i am on a free version i created a (bot) user for the time being.
But i could not get to the root cause of this issue.

**Comment by nfriend** [comment]
@Oloremo @Park0 I recently put together a [tutorial](https://docs.gitlab.com/ee/ci/examples/semantic-release.html) and [example project](https://gitlab.com/gitlab-examples/semantic-release-npm) that uses a project access token (with `api` scope) for authentication. If you're still experiencing this, would you mind taking a quick look at the demo project and see if there's any difference that might be causing this issue?

Another thing to try might be to regenerate the project access token. While putting together the example project, I made a change to the project setup (unfortunately I can't remember what) and my project token stopped working (see https://gitlab.com/gitlab-examples/semantic-release-npm/-/jobs/877587885#L49). I'm not sure why, but regenerating a new token worked in my case 🤷

**Comment by fgreinacher** [comment]
This should work. Feel free to reopen if it still happens for you.
