### ISSUE TITLE
Allow custom names for assets

### ISSUE THREAD

**Issue by leoshusar** [semantic-release/gitlab#167]
Hello, I've seen that `semantic-release/github` has more options for assets, it has `name` property and both properties `name` and `label` are allowed to insert next version by for example `${nextRelease.gitTag}`.

Is something like this planned for this plugin too? 

It would be handy for me because I could've keep my binary archive named like `build.tar.gz` and then rename it to `MyApp-v1.0.0.tar.gz` by this plugin - mainly because `path` property cannot be dynamic even in `github` plugin.

Thank you!

**Comment by nfriend** [comment]
@leoshusar I think this would be a great feature to have 👍 It would be nice to maintain parity with `@semantic-release/github` in this case.

Would you be open to putting together a PR for this?
