### ISSUE TITLE
Use GitLab generic packages repository for assets

### ISSUE THREAD

**Issue by walkafwalka** [semantic-release/gitlab#174]
The [GitLab generic packages repository](https://docs.gitlab.com/ee/user/packages/generic_packages/index.html) is more suited for storing assets related to releases.

And unlike the current project uploads API, the [documentation explicitly states that the CI_JOB_TOKEN has access to the Packages API](https://docs.gitlab.com/ee/api/README.html#gitlab-ci-job-token).

**Comment by nfriend** [comment]
@walkafwalka Thanks for this! I agree that the Generic Package Registry is a better fit. In fact, this is the direction GitLab itself is taking (see https://gitlab.com/gitlab-org/gitlab/-/issues/255271#note_453907441 and https://gitlab.com/gitlab-org/release-cli/-/issues/68).

I would suggest we wait until GitLab has landed on an specific approach and then updating this plugin to mirror its behavior.

**Comment by mikaelkaron** [comment]
I think this has happened now: https://docs.gitlab.com/ee/user/project/releases/#use-a-generic-package-for-attaching-binaries

**Comment by mfoti** [comment]
I have also an error uploading file with size greater than 100Mb:
`[semantic-release] [@semantic-release/gitlab] › ✖  An error occurred while uploading /builds/[...]/MyPackage-1.0.0-amd64.deb to the GitLab project uploads API:`
Can I try to post a PR?

**Comment by fgreinacher** [comment]
This is now possible, thanks to @JonasSchubert work in #343 🎉
