### ISSUE TITLE
Does Not Support Subgroups

### ISSUE THREAD

**Issue by keplersj** [semantic-release/gitlab#2]
GitLab supports subgroups in organizations and parent subgroups. Currently this package assumes a (GitHub-like) `owner/repo` structure, breaking repos following a `organization/group/repo` structure.

**Comment by pvdlg** [comment]
The only I could find regarding the API URL for a repo is: https://docs.gitlab.com/ce/api/README.html#namespaced-path-encoding

Do you have a link to a doc that mention how API URL works for project that are part of an organization?

**Comment by keplersj** [comment]
I can't find any specific documentation but I imagine they're handled the same. For example here's a GitLab repo which follows the `owner/repo` structure: [https://gitlab.com/gitlab-org/gitlab-ce](gitlab-org/gitlab-ce). And here's a repo following the `organization/group/repo` structure: [https://gitlab.com/gitlab-org/gitter/webapp](gitlab-org/gitter/webapp)

Accessing `gitlab-org/gitlab-ce` from the API:
```
GET /api/v4/projects/gitlab-org%2gitlab-ce
```

Accessing `gitlab-org/gitter/webapp` from the API:
```
GET /api/v4/projects/gitlab-org%2gitter%2webapp
```

**Comment by pvdlg** [comment]
Perfect that helps!

Can you confirm that for a repo like https://gitlab.com/gitlab-org/gitter/webapp the `reporisoty.url` in the package.json will be `https://gitlab.com/gitlab-org/gitter/webapp.git` or `git@gitlab.com:gitlab-org/gitter/webapp.git` ?

**Comment by keplersj** [comment]
Both `git@gitlab.com:gitlab-org/gitter/webapp.git` and `https://gitlab.com/gitlab-org/gitter/webapp.git` are valid repo URLs for GitLab repos, so I suppose it'd be up to what the developer sets `repository.url` to. I know that for my use cases I've set `repository.url` to the HTTPS variant.

**Comment by pvdlg** [comment]
Both works with semantic-release, it won't a problem.

My question was related to subgroup and URL. Basically is the API path mirror the Git URL (obtained with `git remote -v`)?

IS the following mapping between web URL and GIT URL is correct:
- https://gitlab.com/a/b => https://gitlab.com/a/b.git
- https://gitlab.com/a/b/c => https://gitlab.com/a/b/c.git
- https://gitlab.com/a/b/c/d => https://gitlab.com/a/b/c/d.git
- etc...

**Comment by keplersj** [comment]
Yes. That mapping is correct.

**Comment by pvdlg** [comment]
One more question, is it possible to have a GitLab private host with a URL like `https://domain.com/context` ?

I imagine in that case the URL in the `pacakge.json` would be `https://domain.com/context/organization/group/repo` but the API access would be:
```
GET /api/v4/projects/organization%2Fgroup%2Frepo
```
And not:
```
GET /api/v4/projects/context%2Forganization%2Fgroup%2Frepo
```
