### ISSUE TITLE
How to deal with ci jobs artifacts?

### ISSUE THREAD

**Issue by existe-deja** [semantic-release/gitlab#228]
Hi,

Thanks for your work on this huge project.

I have a question that I couldn't answer even after reading, docs, faq, recipes, and issues.

How can I add a job artifact into the [@semantic-release/gitlab](https://github.com/semantic-release/gitlab) and the [@semantic-release/git ](https://github.com/semantic-release/git)assets?

Artifacts exemple: 
- build from a previous job
- test coverage

A solution that I didn't fully understand is to run the build into the [@semantic-release/exec](https://github.com/semantic-release/exec) command. This way the dist folder is up to date and I can upload it. I prefer to have one task per job, but anyway. It could work, but I can't afford an extra run of my tests just to pick up the coverage.

Also I always read that semantic-release is not a building tool. I agree with the separation of concerns, so how can I pass artifacts to my semantic-release job?

Thanks

**Comment by nfriend** [comment]
@existe-deja Sorry for the slow response!

You should be able to attach build artifacts as assets to a release using the [`assets` configuration option](https://github.com/semantic-release/gitlab#options).

By default, GitLab will automatically provide the job running `semantic-release` with all build artifacts from previous jobs, so you should just be able to configure your `.releaserc.json` like this:

```json
{
  "plugins": [
    [
      "@semantic-release/gitlab",
      {
        "assets": [{ "path": "path/to/build/artifacts/**/*" }]
      }
    ],
  ]
}
```

[Here's an example of a `.gitlab-ci.yml`](https://gitlab.com/nfriend/semantic-release-test-project/-/blob/8e3a4ead339ebaaf314df1e78e60c294acb6d3bc/.gitlab-ci.yml) that generates some build artifacts in a `build` job, which are then attached to a release when `semantic-release` is run ([here's an example release](https://gitlab.com/nfriend/semantic-release-test-project/-/releases/v1.16.0)). [Here's how this is configured in `.releaserc.json`.](https://gitlab.com/nfriend/semantic-release-test-project/-/blob/8e3a4ead339ebaaf314df1e78e60c294acb6d3bc/.releaserc.json)
