### ISSUE TITLE
Best practice to access to next version tag outside of semantic-release job?

### ISSUE THREAD

**Issue by existe-deja** [semantic-release/gitlab#241]
Hi,

I need to access to the `nextRelease.version` generated tag in my deployment job. Do you have some best practice to share for accessing it?

Thanks

**Comment by nfriend** [comment]
@existe-deja Does this answer your question? https://semantic-release.gitbook.io/semantic-release/support/faq#is-there-a-way-to-preview-which-version-would-currently-get-published

**Comment by existe-deja** [comment]
Kind of. But with the dry-run I have to re-run the release script just for deployment.

I found those two way:
- https://docs.gitlab.com/ee/user/project/push_options.html#push-options-for-gitlab-cicd
- https://docs.gitlab.com/ee/ci/variables/#pass-an-environment-variable-to-another-job

Did you have the chance to use one of them?

Something hard to conceptualize is semantic-release is like a pipeline inside the pipeline. It's often hard to decide witch part should occur under the responsibility of semantic-release or not.

**Comment by nfriend** [comment]
> Something hard to conceptualize is semantic-release is like a pipeline inside the pipeline.

Yes, that's spot on! I've thought the exact same thing.

> Did you have the chance to use one of them?

Yes, I've used the `.env` option in the past for a different use-case. Off the top of my head, I think this is probably the best option to make the version available for jobs that come after the `semantic-release` job.
