### ISSUE TITLE
semantic-release: GotError [HTTPError]: Response code 404 (Not Found)

### ISSUE THREAD

**Issue by anragen** [semantic-release/gitlab#249]
After upgrade gitlab from 13.12 to 14.0 i get an error 

[19:52:30] [semantic-release] › ✖  Failed step "publish" of plugin "@semantic-release/gitlab"
[19:52:30] [semantic-release] › ✖  An error occurred while running semantic-release: GotError [HTTPError]: Response code 404 (Not Found)
    at EventEmitter.<anonymous> (/Users/anri/gitlab/project/node_modules/got/source/as-promise.js:74:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  host: 'gitlab.site.ru',
  hostname: 'gitlab.site.ru',
  method: 'POST',
  path: '/api/v4/projects/project%2Fproject/repository/tags/v2.101.15/release',
  socketPath: undefined,
  protocol: 'https:',
  url: 'https://gitlab.site.ru/api/v4/projects/project%2Fproject/repository/tags/v2.101.15/release',
  gotOptions: {
    path: '/api/v4/projects/project%2Fproject/repository/tags/v2.101.15/release',
    protocol: 'https:',
    slashes: true,
    auth: null,
    host: 'gitlab.site.ru',
    port: null,
    hostname: 'gitlab.site.ru',
    hash: null,
    search: null,
    query: null,
    pathname: '/api/v4/projects/project%2Fproject/repository/tags/v2.101.15/release',
    href: 'https://gitlab.site.ru/api/v4/projects/project%2Fproject/repository/tags/v2.101.15/release',
    retry: {
      retries: [Function],
      methods: [Set],
      statusCodes: [Set],
      errorCodes: [Set]
    },
    headers: {
      'user-agent': 'got/9.6.0 (https://github.com/sindresorhus/got)',
      'private-token': '[secure]',
      accept: 'application/json',
      'accept-encoding': 'gzip, deflate',
      'content-type': 'application/json',
      'content-length': 300
    },
    hooks: {
      beforeRequest: [],
      beforeRedirect: [],
      beforeRetry: [],
      afterResponse: [],
      beforeError: [],
      init: []
    },
    decompress: true,
    throwHttpErrors: true,
    followRedirect: true,
    stream: false,
    form: false,
    json: true,
    cache: false,
    useElectronNet: false,
    body: '{"tag_name":"v2.101.15","description":"## [2.101.15](https://gitlab.site.ru/project/project/compare/v2.101.14...v2.101.15) (2021-06-28)\\n\\n\\n### Bug Fixes\\n\\n* **up:** up ([468fe6e](https://gitlab.site.ru/project/project/commit/468fe6eba21b6d827164c3245b5086cf11228b11))\\n\\n\\n\\n"}',
    method: 'POST'
  },
  statusCode: 404,
  statusMessage: 'Not Found',
  headers: {
    server: 'nginx',
    date: 'Mon, 28 Jun 2021 16:52:30 GMT',
    'content-type': 'application/json',
    'content-length': '25',
    connection: 'close',
    'cache-control': 'no-cache',
    vary: 'Origin',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'SAMEORIGIN',
    'x-request-id': '01F99RJRWCCYCEJ2AT7JT9XTGG',
    'x-runtime': '0.077442'
  },
  body: { error: '404 Not Found' },
  pluginName: '@semantic-release/gitlab'
}
GotError [HTTPError]: Response code 404 (Not Found)
    at EventEmitter.<anonymous> (/Users/anri/gitlab/project/node_modules/got/source/as-promise.js:74:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  host: 'gitlab.site.ru',
  hostname: 'gitlab.site.ru',
  method: 'POST',
  path: '/api/v4/projects/project%2Fproject/repository/tags/v2.101.15/release',
  socketPath: undefined,
  protocol: 'https:',
  url: 'https://gitlab.site.ru/api/v4/projects/project%2Fproject/repository/tags/v2.101.15/release',
  gotOptions: {
    path: '/api/v4/projects/project%2Fproject/repository/tags/v2.101.15/release',
    protocol: 'https:',
    slashes: true,
    auth: null,
    host: 'gitlab.site.ru',
    port: null,
    hostname: 'gitlab.site.ru',
    hash: null,
    search: null,
    query: null,
    pathname: '/api/v4/projects/project%2Fproject/repository/tags/v2.101.15/release',
    href: 'https://gitlab.site.ru/api/v4/projects/project%2Fproject/repository/tags/v2.101.15/release',
    retry: {
      retries: [Function],
      methods: [Set],
      statusCodes: [Set],
      errorCodes: [Set]
    },
    headers: {
      'user-agent': 'got/9.6.0 (https://github.com/sindresorhus/got)',
      'private-token': '[secure]',
      accept: 'application/json',
      'accept-encoding': 'gzip, deflate',
      'content-type': 'application/json',
      'content-length': 300
    },
    hooks: {
      beforeRequest: [],
      beforeRedirect: [],
      beforeRetry: [],
      afterResponse: [],
      beforeError: [],
      init: []
    },
    decompress: true,
    throwHttpErrors: true,
    followRedirect: true,
    stream: false,
    form: false,
    json: true,
    cache: false,
    useElectronNet: false,
    body: '{"tag_name":"v2.101.15","description":"## [2.101.15](https://gitlab.site.ru/project/project/compare/v2.101.14...v2.101.15) (2021-06-28)\\n\\n\\n### Bug Fixes\\n\\n* **up:** up ([468fe6e](https://gitlab.site.ru/project/project/commit/468fe6eba21b6d827164c3245b5086cf11228b11))\\n\\n\\n\\n"}',
    method: 'POST'
  },
  statusCode: 404,
  statusMessage: 'Not Found',
  headers: {
    server: 'nginx',
    date: 'Mon, 28 Jun 2021 16:52:30 GMT',
    'content-type': 'application/json',
    'content-length': '25',
    connection: 'close',
    'cache-control': 'no-cache',
    vary: 'Origin',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'SAMEORIGIN',
    'x-request-id': '01F99RJRWCCYCEJ2AT7JT9XTGG',
    'x-runtime': '0.077442'
  },
  body: { error: '404 Not Found' },
  pluginName: '@semantic-release/gitlab'

**Comment by nfriend** [comment]
@anragen I think it's quite likely this is a result of using an old(ish) version of `@semantic-release/gitlab`. Can you upgrade to version `6.0.7` or higher and let me know if this fixes the issue?

I'm working on a PR that will add some docs about this version incompatibility. For now you can read the details here: https://github.com/semantic-release/gitlab/pull/246/files

I'll close this for now, but please feel free to reopen if this doesn't resolve the issue.

**Comment by anragen** [comment]
@nfriend thanx
