### ISSUE TITLE
semantic-release do not work with gitlab group-token

### ISSUE THREAD

**Issue by radhika-pr** [semantic-release/gitlab#305]
We have a gitlab group and set of projects under that where we want to run release pipelines automatically whenever a tag is created. The pipeline need to be triggered automatically and should be run in different projects. So we used group token to initiate these automatic jobs.
But the job fails with below error
```
Fetching changes with git depth set to 50...
Initialized empty Git repository in /builds/DevHEL/ScaleOut/cooper/.git/
Created fresh repository.
remote: HTTP Basic: Access denied
fatal: Authentication failed for 'https://gitlab.relexsolutions.com/DevHEL/ScaleOut/cooper.git/'
Cleaning up file based variables 00:00
ERROR: Job failed: exit code 1
```

The job will proceed and be successful if we rerun it by any user of the project.
The group token was created with read_repo, write_repo adn api permissions and has been given maintainer access in the project.
The token is used manually to pull and clone the repo which went successful. 
Seems to be issue reported here -https://gitlab.com/gitlab-org/gitlab/-/merge_requests/47247 
But we have gitlab 14.4.1 version running and is stuck with this issue. Appreciate any solution which can be suggested here.

**Comment by nejch** [comment]
This is an upstream issue that was fixed in 14.8 with https://gitlab.com/gitlab-org/gitlab/-/merge_requests/78595. Really no way around it if you use group tokens.

**Comment by fgreinacher** [comment]
Closing this, upgrading GitLab is the only way to fix this.

**Comment by vmasseron** [comment]
Hi, is this an issue ? I've tried using a Project Token with read_repo, write_repo and api permissions but I get `You are not allowed to push code to this project.`
I'm surprised because both MR are merged. I'm using v16.4.1-ee.
Is that normal ?

**Comment by fgreinacher** [comment]
@vmasseron No, this should not happen anymore. Which role does your token have?

**Comment by vmasseron** [comment]
How stupid I am, it just has Guest role…Thanks a lot !Le 21 déc. 2023 à 08:29, Florian Greinacher ***@***.***> a écrit :﻿
@vmasseron No, this should not happen anymore. Which role does your token have?

**Comment by fgreinacher** [comment]
No worries! Been there, done that :)
