### ISSUE TITLE
How get release message on merge request?

### ISSUE THREAD

**Issue by borisdamevin** [semantic-release/gitlab#330]
This message is not write on merge request. Is normal or I miss something?

```
🎉 This PR is included in version x.x.x 🎉

The release is available on:

    npm package (@latest dist-tag)
    GitHub release

Your semantic-release bot 📦🚀
```

**Comment by fgreinacher** [comment]
This feature is not implemented at the moment, similar to #40.

I am working on it in #332.

**Comment by borisdamevin** [comment]
@fgreinacher Any new about your PR?

**Comment by fgreinacher** [comment]
@borisdamevin It is ready, but is waiting for maintainer review.

**Comment by TilmannBach** [comment]
fgreinacher thanks for your work in this! 🚀

**Comment by fgreinacher** [comment]
This is working in [v8.0.0](https://github.com/semantic-release/gitlab/releases/tag/v8.0.0) and above.
