### ISSUE TITLE
Removing myself as maintainer of semantic-release/gitlab

### ISSUE THREAD

**Issue by nfriend** [semantic-release/gitlab#333]
Hey @semantic-release! Just wanted to let you know I'm going to be removing myself as a maintainer of `semantic-release/gitlab`. I no longer work at GitLab and haven't been able to find time to prioritize reviews or maintenance tasks.

Thanks for your ongoing work on this fantastic project! 🙏 🏅

**Comment by travi** [comment]
thank you so much for your help while you were able. we really appreciate it and you made an important impact. don't hesitate to let us know if you want to come back in an official capacity at some point. obviously, you are always welcome to provide input in an unofficial capacity at any time as well.
