### ISSUE TITLE
successComment has bad formatted emojis

### ISSUE THREAD

**Issue by baby-gnu** [semantic-release/gitlab#344]
Hello.

There should be a space between `:package:` and `:rocket` because they are not displayed on my 14.6 self hosted gitlab.

![semantic-release-gitlab-successComment-emoji-fail](https://user-images.githubusercontent.com/1233212/159498495-b0a7a52c-1a09-45ed-9f7e-644cff71c846.png)

Thanks.

**Comment by TilmannBach** [comment]
there is another bug in the comment: the link to the gitlab release does not work correctly:
![image](https://user-images.githubusercontent.com/2125941/159913503-0cd7ecaf-7d04-49cf-b7a4-cd6afb5e665c.png)
this `%2F` should be a slash instead

**Comment by JonasSchubert** [comment]
#342 would fix both issues
