### ISSUE TITLE
Which package is correct?

### ISSUE THREAD

**Issue by joshdcomp** [semantic-release/gitlab#35]
Hi! I'm a bit confused…there are two packages in NPM purporting to be _the_ Semantic Release Gitlab publisher—this one, called `@semantic-release/gitlab` and another called  `semantic-release-gitlab`, can you give some clarification as to what the difference is?

**Comment by pvdlg** [comment]
`@semantic-release/gitlab` is a plugin to support releases on GitLab. It is part of the `semantic-release` organization and maintain by the same team.

`semantic-release-gitlab` is not affiliated with semantic-release. I cannot speak for what it is or what it does.

**Comment by joshdcomp** [comment]
@pvdlg thanks for the quick response! For posterity Hutson Betts is the maintainer for the other package, his [response is here](https://gitlab.com/hyper-expanse/open-source/semantic-release-gitlab/issues/41), notably:

> semantic-release-gitlab is a command-line tool that publishes releases to GitLab (semantic-release-gitlab was written before there was a GitLab plugin for the semantic-release tool)

**Comment by joshdcomp** [comment]
That said, seems the official package is here, for my money this is the 'correct' one to use. Closing :D
