### ISSUE TITLE
Response code 429 (Too Many Requests) on successComment

### ISSUE THREAD

**Issue by vgropp** [semantic-release/gitlab#361]
We are running into the gitlab API limit on some projects when multiple semantic-releases are running at the same time from share IPs.

```
[8:07:42 AM] [semantic-release] › ℹ  Start step "success" of plugin "@semantic-release/gitlab"
[8:07:44 AM] [semantic-release] [@semantic-release/gitlab] › ✖  An error occurred while posting comments to related issues and merge requests:
HTTPError: Response code 429 (Too Many Requests)
    at Request.<anonymous> (/usr/local/lib/node_modules/@semantic-release/gitlab/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
```

As far as I understand the code https://github.com/semantic-release/gitlab/blob/3051799160efc127585d30a4ef776ccf34185fee/lib/success.js#L72 for very Commit the script is looking for a MR, with those MR the script is searching for an resolved issue. So there will be at least  commits * MR Requests. As we do not use gitlab issues (but like the MR comment), what about a configuration to disable the Issue Comments and hence those requests? This will limit the requests to count of commits. 

Another Option would be rate limiting the requests, but that seems like a lot more work but more sustainable solution.

**Comment by fgreinacher** [comment]
Thanks for reporting this @vgropp!

You can disable the new feature by setting the `successComment` option to `false`. 

Other than that I think it would make sense to add proper handling of such cases to this plugin.

**Comment by fgreinacher** [comment]
@vgropp Have you seen this behavior recently? In https://github.com/semantic-release/gitlab/pull/728 we learned that the underlying HTTP library does actually have a quite powerful retry logic. I'd like to understand why this is not enough in your case. 🙇

**Comment by liz72703** [comment]
I got this error today.  Never happened before.

AggregateError: 
    HTTPError: Response code 429 (Too Many Requests)
        at Request.<anonymous> (file:///builds/fidus-global/pontem-ui/node_modules/got/dist/source/as-promise/index.js:92:42)
        at Request._onResponseBase (file:///builds/fidus-global/pontem-ui/node_modules/got/dist/source/core/index.js:604:22)
        at async Request._onResponse (file:///builds/fidus-global/pontem-ui/node_modules/got/dist/source/core/index.js:646:13)
    at file:///builds/fidus-global/pontem-ui/node_modules/semantic-release/lib/plugins/pipeline.js:55:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async pluginsConfigAccumulator.<computed> [as success] (file:///builds/fidus-global/pontem-ui/node_modules/semantic-release/lib/plugins/index.js:87:11)
    at async run (file:///builds/fidus-global/pontem-ui/node_modules/semantic-release/index.js:218:3)
    at async Module.default (file:///builds/fidus-global/pontem-ui/node_modules/semantic-release/index.js:278:22)
    at async default (file:///builds/fidus-global/pontem-ui/node_modules/semantic-release/cli.js:55:5) {
  errors: [
    HTTPError: Response code 429 (Too Many Requests)
        at Request.<anonymous> (file:///builds/fidus-global/pontem-ui/node_modules/got/dist/source/as-promise/index.js:92:42)
        at Object.onceWrapper (node:events:633:26)
        at Request.emit (node:events:530:35)
        at Request._onResponseBase (file:///builds/fidus-global/pontem-ui/node_modules/got/dist/source/core/index.js:604:22)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async Request._onResponse (file:///builds/fidus-global/pontem-ui/node_modules/got/dist/source/core/index.js:646:13) {
      input: undefined,
      code: 'ERR_NON_2XX_3XX_RESPONSE',
      timings: [Object],
      options: {
        request: undefined,
        agent: { http: undefined, https: undefined, http2: undefined },
        h2session: undefined,
        decompress: true,
        timeout: {
          connect: undefined,
          lookup: undefined,
          read: undefined,
          request: undefined,
          response: undefined,
          secureConnect: undefined,
          send: undefined,
          socket: undefined
        },
        prefixUrl: '',
        body: '{"body":":tada: This MR is included in version 5.5.0 :tada:\\n\\nThe release is available on [GitLab release](https://gitlab.com/fidus-global/pontem-ui.git/fidus-global/pontem-ui/-/releases/v5.5.0).\\n\\nYour **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package: :rocket:"}',
        form: undefined,
        json: undefined,
        cookieJar: undefined,
        ignoreInvalidCookies: [secure],
        searchParams: undefined,
        dnsLookup: undefined,
        dnsCache: undefined,
        context: {},
        hooks: {
          init: [],
          beforeRequest: [],
          beforeError: [],
          beforeRedirect: [],
          beforeRetry: [],
          afterResponse: []
        },
        followRedirect: true,
        maxRedirects: 10,
        cache: undefined,
        throwHttpErrors: true,
        username: '',
        password: '',
        http2: [secure],
        allowGetBody: [secure],
        headers: {
          'user-agent': 'got (https://github.com/sindresorhus/got)',
          'private-token': '[secure]',
          'content-type': 'application/json',
          'content-length': '306',
          'accept-encoding': 'gzip, deflate, br'
        },
        methodRewriting: [secure],
        dnsLookupIpVersion: undefined,
        parseJson: [Function: parse],
        stringifyJson: [Function: stringify],
        retry: {
          limit: 2,
          methods: [ 'GET', 'PUT', 'HEAD', 'DELETE', 'OPTIONS', 'TRACE' ],
          statusCodes: [
            408, 413, 429, 500,
            502, 503, 504, 521,
            522, 524
          ],
          errorCodes: [
            'ETIMEDOUT',
            'ECONNRESET',
            'EADDRINUSE',
            'ECONNREFUSED',
            'EPIPE',
            'ENOTFOUND',
            'ENETUNREACH',
            'EAI_AGAIN'
          ],
          maxRetryAfter: undefined,
          calculateDelay: [Function: calculateDelay],
          backoffLimit: Infinity,
          noise: 100
        },
        localAddress: undefined,
        method: 'POST',
        createConnection: undefined,
        cacheOptions: {
          shared: undefined,
          cacheHeuristic: undefined,
          immutableMinTimeToLive: undefined,
          ignoreCargoCult: undefined
        },
        https: {
          alpnProtocols: undefined,
          rejectUnauthorized: undefined,
          checkServerIdentity: undefined,
          certificateAuthority: undefined,
          key: undefined,
          certificate: undefined,
          passphrase: undefined,
          pfx: undefined,
          ciphers: undefined,
          honorCipherOrder: undefined,
          minVersion: undefined,
          maxVersion: undefined,
          signatureAlgorithms: undefined,
          tlsSessionLifetime: undefined,
          dhparam: undefined,
          ecdhCurve: undefined,
          certificateRevocationLists: undefined
        },
        encoding: undefined,
        resolveBodyOnly: [secure],
        isStream: [secure],
        responseType: 'text',
        url: URL {
          href: 'https://gitlab.com/api/v4/projects/51037352/merge_requests/360/notes',
          origin: 'https://gitlab.com',
          protocol: 'https:',
          username: '',
          password: '',
          host: 'gitlab.com',
          hostname: 'gitlab.com',
          port: '',
          pathname: '/api/v4/projects/51037352/merge_requests/360/notes',
          search: '',
          searchParams: URLSearchParams {},
          hash: ''
        },
        pagination: {
          transform: [Function: transform],
          paginate: [Function: paginate],
          filter: [Function: filter],
          shouldContinue: [Function: shouldContinue],
          countLimit: Infinity,
          backoff: 0,
          requestLimit: 10000,
          stackAllItems: [secure]
        },
        setHost: true,
        maxHeaderSize: undefined,
        signal: undefined,
        enableUnixSockets: [secure]
      },
      pluginName: '@semantic-release/gitlab',
      [cause]: {}
    }
  ]
}
Cleaning up project directory and file based variables
00:01
ERROR: Job failed: exit code 1

**Comment by schraal** [comment]
Got this error last week

**Comment by jakec-dev** [comment]
Getting this error now

**Comment by nejch** [comment]
Just ran into this as well: https://gitlab.com/marge-org/marge-bot/-/pipelines/1554783088

Not a big deal though as the rest of the release is done before and this probably only happens when not releasing often or on the first release when it spams all the issues/MRs.

**Comment by OZIOisgood** [comment]
Got this error today

**Comment by nejch** [comment]
If all the recent issues reported here are happening on gitlab.com, it could also be that their infrastructure has changed to more aggressive rate limits that the client can't always handle properly anymore.

**Comment by fgreinacher** [comment]
@OZIOisgood @jakec-dev @schraal @liz72703 Do you remember whether the errors happened on the first release, when `semantic-release` tried to comment a lot of issues/MRs?

**Comment by fgreinacher** [comment]
We could try to increase the maximum number of retries, similar to how it was originally suggested in https://github.com/semantic-release/gitlab/pull/728#discussion_r1623432743. Right now got will give up after 2 retries.

/cc @JonasSchubert

**Comment by jakec-dev** [comment]
@fgreinacher Yes, for our team this only occurs on the first release. Subsequent releases are fine.

**Comment by fgreinacher** [comment]
Folks, please upgrade to [13.2.3](https://github.com/semantic-release/gitlab/releases/tag/v13.2.3) where we increased the retry limit. You can also play with the new `retryLimit` option to tune the behavior further.
