### ISSUE TITLE
SSH key based authentication instead of personal access token

### ISSUE THREAD

**Issue by DanielMcKracken** [semantic-release/gitlab#377]
Dear all,

I managed to enabled the ssh authentication for my project - from the pipeline log I can see that semantic-release is successfully checking the ssh connection:
`semantic-release:get-git-auth-url Verifying ssh auth by attempting to push to  git@gitlab.com:mygroup/myproject.git`

But as soon as the gitlab plugin is involved to publish the gitlab release the following error occurs:
```
[7:36:53 AM] [semantic-release] › ✖  ENOGLTOKEN No GitLab token specified.
A GitLab personal access token (https://github.com/semantic-release/gitlab/blob/master/README.md#gitlab-authentication) must be created and set in the GL_TOKEN or GITLAB_TOKEN environment variable on your CI environment.
[...]
AggregateError: 
    SemanticReleaseError: No GitLab token specified.
```

Is it possible to use ssh key based authentication instead of personal access token when using the Gitlab plugin?

Thank you very much!

**Comment by fgreinacher** [comment]
This is unfortunately not possible, because we're using the GitLab API which does not support SSH auth.
