### ISSUE TITLE
How to use semantic release generated version in Gitlab CI/CD ?

### ISSUE THREAD

**Issue by softshape** [semantic-release/gitlab#378]
There is a phrase in GitLab docs -

> As part of publishing a package, semantic-release increases the version number in package.json.

Our semantic release succesfully updates changelog.md, but in the package.json version remains "0.0.0". Is there any config we need to setup to make it update version in package.json ?

**Comment by tobiasbaehr** [comment]
I did not found this phrase in the repo README, but this FAQ should answer your question(s) https://github.com/semantic-release/semantic-release/blob/master/docs/support/FAQ.md#why-is-the-packagejsons-version-not-updated-in-my-repository

**Comment by softshape** [comment]
Well it's not really clear. `"private": true` is already set in my package.json. FAQ states "the [@semantic-release/git](https://github.com/semantic-release/git) plugin can be used to push the updated package.json as well as other files to the Git repository." but doesn't clarify how.

**Comment by softshape** [comment]
May be there is any other way to read the version set by semantic release from Gitlab build script?

**Comment by JonasSchubert** [comment]
Do you use a configuration file? E.g. `.releaserc.json`?
It can look similar to this:

```json
{
  "branches": [
    "main",
    {
      "channel": "beta",
      "name": "dev",
      "prerelease": "beta"
    }
  ],
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/changelog",
    "@semantic-release/gitlab",
    "@semantic-release/npm",
    [
      "@semantic-release/git",
      {
        "assets": [
          "package.json",
          "package-lock.json",
          "CHANGELOG.md"
        ],
        "message": "chore(release): ${nextRelease.version}\n\n${nextRelease.notes}"
      }
    ]
  ]
}
```

Version releases are running on branch `main`, beta releases on branch `dev`.
Plugin `npm` manipulates `package.json` and `package-lock.json` and plugin `git` commits the changed files.

**Comment by softshape** [comment]
Thank you Jonas! Your config solved the problem (there was no npm plugin in my .releaserc)

**Comment by fgreinacher** [comment]
Problem seems to be solved, so I'm closing this. Feel free to reopen if necessary!
