### ISSUE TITLE
Tag is already created with semantic-release

### ISSUE THREAD

**Issue by Begi** [semantic-release/gitlab#39]
Git tag is already created before the "publish" step with semantic-release

https://github.com/semantic-release/semantic-release/blob/b89523105cf04298f1f44858a02cc76c6c5dd0a5/index.js#L106
```
// Create the tag before calling the publish plugins as some require the tag to exists
    await tag(nextRelease.gitTag, {cwd, env});
    await push(options.repositoryUrl, options.branch, {cwd, env});
    logger.success(`Created tag ${nextRelease.gitTag}`);

    context.releases = await plugins.publish(context);
```
So the POST request fails when creating the tag.

Instead PUT request will update the created tag with associated notes

**Comment by pvdlg** [comment]
Closing as it seems there is no issue and no answer was provided.
