### ISSUE TITLE
How to write version to any file other than package.json ?

### ISSUE THREAD

**Issue by softshape** [semantic-release/gitlab#399]
As we know npm plugin can write version to the package.json file in a root folder. Is there any way to configure semantic release to:

1. write version to any other JSON file, say version.json ?
2. write it to non-JSON file, for example in Yaml format?
3. write version to a file not in the root folder?

So far I've no success in any of that.

The real problem is that the root files in my project are not accessible after build, and its Java so its version is currently stored in build.gradle file which is Yaml.

**Comment by JonasSchubert** [comment]
I see two options here:

1. Use a custom plugin which fulfills your need of updating a version in build.gradle
  a. There is for example [this](https://github.com/KengoTODA/gradle-semantic-release-plugin) one, but this requires your version in `gradle.properties`
  b. Right your own plugin which handles this
2. Use [semantic-release/exec](https://github.com/semantic-release/exec) and write your own scripts

**Comment by fgreinacher** [comment]
I fully agree with what @JonasSchubert says.

I'll close this issue as it's not really related to the gitlab plugin. Feel free to open a new issue in the main repo https://github.com/semantic-release/semantic-release.
