### ISSUE TITLE
create only tags?

### ISSUE THREAD

**Issue by IGZangelcostales** [semantic-release/gitlab#405]
Hi team,

I looking for a way to just create the tags with semantic-release, but I don't want to publish a release in GitLab after the tag. it's possible? How can I do it?

Thank you very much in advance.

**Comment by r4j4h** [comment]
I think in that case you would just want to use the @semantic-release/git plugin and not the @semantic-release/gitlab plugin

**Comment by fgreinacher** [comment]
Closing this as it has been answered, feel free to reopen if anything is still unclear.
