### ISSUE TITLE
asset url containing ${nextRelease.version} not working/expanded

### ISSUE THREAD

**Issue by jagiella** [semantic-release/gitlab#406]
I would like to create version dependent `url`s as release assets pointing to the specific file on an other filehosting server.

```json
["@semantic-release/gitlab", {
      "assets": [
          {"url": "http://fileserver/${nextRelease.version}/update.zip", "label": "update file", "type": "other"}
      ]
}]
```

The release page nevertheless will contain the following link:
```
http://fileserver/$%7BnextRelease.version%7D/update.zip
```

For the asset label that seems to work as the [documentation suggests](https://github.com/semantic-release/gitlab#usage), e.g.
```json
{"path": "dist/asset.min.js", "label": "v${nextRelease.version}.js"}
```

But why not for the `url`?

**Comment by fgreinacher** [comment]
This absolutely makes sense!

Happy to take a PR, probably very similar to https://github.com/semantic-release/gitlab/pull/365.
