### ISSUE TITLE
How upload JS files (error 422)

### ISSUE THREAD

**Issue by oliveirarafa** [semantic-release/gitlab#422]
For what I figured, gitlab blocks uploaded .js files because of security.

The documentation tells me to use a glob to get all files from my dist folder my gitlab returns a page like this:

![image](https://user-images.githubusercontent.com/35575006/178088049-559c6c3e-32b8-409a-82f0-fc477d3284b4.png)

Is there a way to include the .js files directly in the assets section instead of making a zip with all of them?

**Comment by fgreinacher** [comment]
We don't support that natively, sorry. Could you zip your assets as part of your build and reference the zip instead?

**Comment by oliveirarafa** [comment]
Yes. I did that but I think it would be better to upload js directly. But no problem, i'll keep making a zip file. Thanks.
