### ISSUE TITLE
better use version instead of git tag for publishing generic package?

### ISSUE THREAD

**Issue by manlao** [semantic-release/gitlab#502]
# Current

generic package use git tag as package_version

<img width="412" alt="image" src="https://user-images.githubusercontent.com/1523671/218632478-79a57352-a865-478d-89c6-f3dbf106f47e.png">

# Expected

according to [gitlab docs](https://docs.gitlab.com/ee/user/packages/generic_packages/), better use version instead?

<img width="875" alt="image" src="https://user-images.githubusercontent.com/1523671/218636003-b8ffc8bc-7c91-4e1e-9de2-4c745ffd12b8.png">

**Comment by JonasSchubert** [comment]
Using `semantic-release` the git tag and package version should be the same. I didn't stumble upon anything different yet. 
Do you have an use case where they differ?

**Comment by manlao** [comment]
> Using `semantic-release` the git tag and package version should be the same. I didn't stumble upon anything different yet. Do you have an use case where they differ?

I tried to download a package file with release version number only ([nextRelease.version](https://github.com/semantic-release/semantic-release/blob/master/docs/developer-guide/plugin.md#verifyrelease)) using [gitlab package api](https://docs.gitlab.com/ee/api/packages.html#delete-a-package-file), then found the package version is release version number with `v` ([nextRelease.gitTag](https://github.com/semantic-release/semantic-release/blob/master/docs/developer-guide/plugin.md#verifyrelease)).

I think it's better to document it or be consistent with version number.

Thanks

**Comment by JonasSchubert** [comment]
@manlao thanks for the explanation and the catch.
I think you are correct. Also to be consistent with `semantic-release/npm` we should use the version instead of the git tag. Will fix this.

**Comment by fgreinacher** [comment]
I agree, let’s go for consistency 👍

**Comment by JonasSchubert** [comment]
@manlao Thanks for pointing out the inconsistency. PR is created.

**Comment by fgreinacher** [comment]
This has been fixed.
