### ISSUE TITLE
Assets on release tag

### ISSUE THREAD

**Issue by vxcamiloxv** [semantic-release/gitlab#54]
Similar to semantic-release/github, it would be awesome if the gitlab package add a assets on the release notes: see this API endpoint https://docs.gitlab.com/ce/api/projects.html#upload-a-file

**Comment by pvdlg** [comment]
According to the doc you linked this API function is for uploading "a file to the specified project to be used in an issue or merge request description, or a comment" and not for adding assets to a release.

So it doesn't seems to be possible at the moment to add files to a release.

**Comment by vxcamiloxv** [comment]
But, for the release is the same to comments or merge request, when you add a file in the tag the results are the same, for example, this file was uploaded manually from the tag editor.

```
[SimpleEmail-v1.1.0-release.apk](/uploads/7340dacd13feda17c9d761e7be97cd66/SimpleEmail-v1.1.0-release.apk)
```
the result when you use an `upload` endpoint is the same `/uploads/hash/...`

![screenshot-2018-11-13_12-41-13](https://user-images.githubusercontent.com/14242544/48432173-a57b1e80-e741-11e8-8c5e-4259902ae3dd.png)

**Comment by pvdlg** [comment]
So we would need to upload the file, get the auto-generated link and add that at the bottom of the release message?
That seems kind of a workaround but why not. Do you know if there is any plan/opened issue in GitLab for adding a proper API for releases similar to the one in GitHub?

**Comment by vxcamiloxv** [comment]
@pvdlg a GitLab development says: "Actually, GitLab already supports this feature. In GitLab, the release notes are implemented basically as a markdown note, similar to issues or merge requests. These markdown notes support uploads. To attach a file to the release, you have to link it in the release notes. So the first step is uploading a file via the API, which is returning the upload directory as well as a markdown formatted link and then create a release including that link." 

https://gitlab.com/gitlab-org/gitlab-ce/issues/3857
