### ISSUE TITLE
Generated links use legacy routes and stopped working

### ISSUE THREAD

**Issue by Tlepel** [semantic-release/gitlab#541]
The generated links for Gitlab issues, commits etc. still use legacy routes. In https://gitlab.com/gitlab-org/gitlab/-/issues/28848 the new routes are stipulated, so they need to be changed in this repository to keep the generated release notes working

**Comment by milo526** [comment]
I don't believe this is a problem with this package.

It seems to be a problem in conventional-changelog.
See also https://github.com/conventional-changelog/conventional-changelog/issues/986

**Comment by travi** [comment]
see also: https://github.com/semantic-release/release-notes-generator/issues/449

**Comment by fgreinacher** [comment]
I'm closing this one. Follow https://github.com/semantic-release/release-notes-generator/issues/449 for updates.
