### ISSUE TITLE
Inspect Submodule changes

### ISSUE THREAD

**Issue by akowi-sknobloch** [semantic-release/gitlab#564]
Hello everyone,

Im testing around with generating Javascript Libraries for gRPC Proto files.
My setup consists of 3 Separate Gitlab Projects.
1. The Project containing my proto files
2. A Project to build a npm Package to be used in NestJS
3. A Project to build a npm Package to be used in the Webbrowser

Project 1. get's referenced as a Submodule by the other two projects.
Project 1. contains a simple `.gitlab-ci.yml` that triggers the pipelines of the other two project.
Project 2. & 3. have a `.gitlab-ci.yml` to build the packages and create a npm release via semantic-release.

When pushing a commit to the projects 2 & 3 everything is good and semantic-release publishes a new version.
When pushing to project 1 the other to pipelines get triggered but do not release a new version.
Seems like semantic-release is not recognizing the commit on the submodule as the Log contains following line:
```
[semantic-release] › ℹ  There are no relevant changes, so no new version is released.
```

I'm guessing that this is expected behaviour.
Therefore my Question, is there a config option or a Plugin to inspect submodule changes?

My current ` .releaserc.json` for project 2 & 3 looks like this:
```json
{
  "branches": ["main"],
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/gitlab",
    "@semantic-release/npm",
    [
      "@semantic-release/git",
      {
        "assets": ["package.json"],
        "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
      }
    ]
  ]
}
```

**Comment by travi** [comment]
> I'm guessing that this is expected behaviour.
> Therefore my Question, is there a config option or a Plugin to inspect submodule changes?

you are correct that this is expected behavior. there is no config option to trigger inspection of submodule changes. without knowing enough about your project, it seems like it would potentially be better to have an npm package published for project 1 that is a dependency of the npm packages fro projects 2 & 3? that way, incrementing the version of the project-1 dependency in projects 2 & 3 would result in a valid commit to trigger releases in 2 & 3. you could even automate such coordination with a tool like Renovate

**Comment by akowi-sknobloch** [comment]
I've switched to using [multi-semantic-release](https://github.com/dhoulb/multi-semantic-release).
Now my Project consists of a monorepo containing 3 packages.
One for the proto files
One for NestJS
One for the Browser

That way i now get 3 separate npm packages released to my registry.
