### ISSUE TITLE
Possibility to send succesMessage only for Issue

### ISSUE THREAD

**Issue by Hakihiro** [semantic-release/gitlab#636]
Hi, first, thanks for your work on this project.

Second, I'm guessing if there is any possibility to disable success message but only for issue or MR ?

Because right now it's quite redundant to have the message in the issue and MR. And we can only disable success message for both, but not only for one of them.

If not, is this something you will be open to have in the project.

Sorry if this message is silly, I could not find any information about it.

**Comment by Hakihiro** [comment]
Hi, thanks for your response.

Your proposal seems to be (in my case), what I need.

I don't see this as something complicated either for the utilization or the implementation, are you open to PR or should we wait the approval of the team about it?

**Comment by JonasSchubert** [comment]
Hey @Hakihiro , personally, I would wait for team response before starting to work on that.
There have been some discussions related to similar topics and maybe we can bundle it somehow.

But doesn't mean you shouldn't start working on that or anybody else 😉

**Comment by fgreinacher** [comment]
Thanks for reaching out @Hakihiro!

I think we should first explore the suggestion by @olexs at https://github.com/semantic-release/gitlab/issues/480#issuecomment-1446450041 as this would be most flexible while keeping the configuration surface small.

Feel free to send a PR for this so that we can see how that would feel.

**Comment by Hakihiro** [comment]
Hi, sorry for the delay.

I made it quickly (really inspired by @JonasSchubert suggestion, thanks btw) just to validate the global design. If it's validate by the team, I can add tests and take code feedbacks to improve the modifications, and the documentation ofc.

I think it could be a first step, and it could be overridden later by an information extracted from the comment template.
This way is really the more natural for the user to have an explicit way to configure it, and it can really be easier to understand from a documentation.

I'm open to discuss it.

Thanks again for your time

**Comment by fgreinacher** [comment]
@Hakihiro The new option `successCommentCondition` should do the job 😀

**Comment by Hakihiro** [comment]
Thanks to all contributors for this one, sorry to not following the work, I wasn't able to do it before.
