### ISSUE TITLE
Publish links instead of files

### ISSUE THREAD

**Issue by joonhwa** [semantic-release/gitlab#65]
My project is building and releasing containers. How can i show links in the release notes? Currently it shows a list of files but is not ideal in my case as i rather have a link to an image in the container registry.

**Comment by joonhwa** [comment]
hi.. my apologies.. i should have provided more details.

So my project is primarily concerned with building Docker images and hosting them from Gitlab Container Registry. The ci job now runs in 3 stages: build, test, tag. During the tagging stage i would like to automatically git tag that particular commit to make it as a release and also generate a release note. I managed to get everything running so far but what i wanted in the release note is to be able to create some text to point users to that new image in the Container Registry. In my case, my users do not really need to have the uploaded src files.

Hope this clarifies...

**Comment by pvdlg** [comment]
Ok I understand. So the only solution is to create a custom `generateNotes` plugin that would append the link you want to add to the release note.

Alternatively you can do that with a script using the `@semantic-release/exec` plugin and setting the `generateNotesCmd` option to point to a script that would output the link you want to append to the release note.

**Comment by joonhwa** [comment]
ok cool... i will give that a try.. thanks!
