### ISSUE TITLE
Inconsistent link to release on email from semantic-release bot

### ISSUE THREAD

**Issue by kpturner** [semantic-release/gitlab#697]
When a release is created, semantic release bot sends an email that looks like this

![image](https://github.com/semantic-release/gitlab/assets/308646/6efc5339-9575-4693-9ecb-66fcf7e0528f)

where it says `The release is available on` followed by a link to the GitHub release.

However, for one of our packages, although a release is created in GitHub, the email looks like this

![image](https://github.com/semantic-release/gitlab/assets/308646/cb5200bc-a7d8-4c7c-ab0c-1d5850b53d33)

So instead of a link it is effectively a piece of text.  I am trying to fathom out what on earth would cause this difference. Can anybody shed any light?

**Comment by fgreinacher** [comment]
Thanks for creating the issue @kpturner. This repository is for the Git**Lab** plugin though. I think you want to move this over to https://github.com/semantic-release/github :)
