### ISSUE TITLE
Support for CI_JOB_TOKEN instead of GL_TOKEN or GITLAB_TOKEN env var being setup

### ISSUE THREAD

**Issue by arkhoss** [semantic-release/gitlab#724]
Hi everyone! thanks for the plugin, it does quite a nice job, that being said, I would like to ask for a feature or support of a CI predefined variable, called `CI_JOB_TOKEN`.

When a CI/CD pipeline job is about to run, GitLab generates a unique token and makes it available to the job as the [CI_JOB_TOKEN predefined variable](https://docs.gitlab.com/ee/ci/variables/predefined_variables.html). The token is valid only while the job is running. After the job finishes, the token access is revoked and you cannot use the token anymore.

I've tried a pipeline using variables like:

```
job:
--- snip ---
variables:
  GITLAB_TOKEN: ${CI_JOB_TOKEN}
```

also tried,

```
script:
  - export GITLAB_TOKEN=${CI_JOB_TOKEN}
  - npx semantic-release
```

but in both cases, I get errors in the Job related to `EINVALIDGLTOKEN` from verify.js file at: https://github.com/semantic-release/gitlab/blob/master/lib/verify.js#L84

Now, It might be me doing something wrong or lack of understanding of the `GITLAB_TOKEN` and `GL_TOKEN` variables, but I believe this should achieved without need to static assign a value or token in the CI/CD variables of the project or group. 

imho, a dynamic token like `CI_JOB_TOKEN` it might be a better approach. If this is already supported please then close this request. Thanks!

**Comment by JonasSchubert** [comment]
See also https://github.com/semantic-release/gitlab/issues/156

**Comment by fgreinacher** [comment]
As @JonasSchubert mentions above this is the same request as https://github.com/semantic-release/gitlab/issues/156 which was closed in favor of the more general semantic-release issue https://github.com/semantic-release/semantic-release/issues/1729. I'm therefore also going to close this one. Feel free to subscribe for the semantic-release issue for updates 🙇
