### ISSUE TITLE
Error: No token provided for GitLab

### ISSUE THREAD

**Issue by aldinei-sampaio** [semantic-release/gitlab#73]
I am receiving the following error:

`semantic-delivery-gitlab failed for the following reason - Error: No token provided for GitLab.`

Both the environment variables GITLAB_TOKEN and GL_TOKEN are defined. I am running on Windows.

![image](https://user-images.githubusercontent.com/7284431/58203892-87264a80-7cb1-11e9-8eed-4e439153c166.png)

**Comment by pvdlg** [comment]
I don't know what `semantic-delivery-gitlab` is but that's not that project.
You should open issue in the repo of the tool you are using.
