### ISSUE TITLE
An error occurred while running gitlab from 17.1.2 to 17.2.0 in a docker container

### ISSUE THREAD

**Issue by socza** [semantic-release/gitlab#751]
I have a error when I started gitlab 17.1.2 to 17.2.0

Caused by:
PG::DependentObjectsStillExist: ERROR:  cannot drop desired object(s) because other objects depend on them
DETAIL:  default value for column project_id of table status_page_settings depends on sequence status_page_settings_project_id_seq
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
/opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/migration_helpers.rb:776:in `block in revert_initialize_conversion_of_integer_to_bigint'
/opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/migration_helpers.rb:776:in `each'
/opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/migration_helpers.rb:776:in `revert_initialize_conversion_of_integer_to_bigint'
/opt/gitlab/embedded/service/gitlab-rails/db/post_migrate/20240709014310_cleanup_bigint_conversions_for_p_ci_builds_attempt2.rb:28:in `up'
/opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/migration_helpers/restrict_gitlab_schema.rb:33:in `block in exec_migration'
/opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/query_analyzer.rb:40:in `within'
/opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/migration_helpers/restrict_gitlab_schema.rb:30:in `exec_migration'
/opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/migration_helpers/automatic_lock_writes_on_tables.rb:21:in `exec_migration'
/opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/with_lock_retries.rb:123:in `run_block'
/opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/with_lock_retries.rb:134:in `block in run_block_with_lock_timeout'
/opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/connection_proxy.rb:127:in `public_send'
/opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/connection_proxy.rb:127:in `block in write_using_load_balancer'
/opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/load_balancer.rb:141:in `block in read_write'
/opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/load_balancer.rb:228:in `retry_with_backoff'
/opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/load_balancer.rb:130:in `read_write'
/opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/connection_proxy.rb:126:in `write_using_load_balancer'
/opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/connection_proxy.rb:78:in `transaction'
/opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/with_lock_retries.rb:129:in `run_block_with_lock_timeout'
/opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/with_lock_retries.rb:97:in `run'
/opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/migrations/lock_retry_mixin.rb:52:in `ddl_transaction'
/opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/migrations/runner_backoff/active_record_mixin.rb:21:in `execute_migration_in_transaction'
/opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/migrations/pg_backend_pid.rb:15:in `block in with_advisory_lock_connection'
/opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/migrations/pg_backend_pid.rb:12:in `with_advisory_lock_connection'
/opt/gitlab/embedded/service/gitlab-rails/lib/tasks/gitlab/db.rake:136:in `configure_database'
/opt/gitlab/embedded/service/gitlab-rails/lib/tasks/gitlab/db.rake:107:in `configure_pg_databases'
/opt/gitlab/embedded/service/gitlab-rails/lib/tasks/gitlab/db.rake:94:in `block (3 levels) in <top (required)>'
/opt/gitlab/embedded/bin/bundle:25:in `load'
/opt/gitlab/embedded/bin/bundle:25:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
Running db:migrate rake task
main: == [advisory_lock_connection] object_id: 53240, pg_backend_pid: 577
main: == 20240709014310 CleanupBigintConversionsForPCiBuildsAttempt2: migrating =====
main: -- current_schema(nil)
main:    -> 0.0007s
main: -- column_exists?(:p_ci_builds, "auto_canceled_by_id_convert_to_bigint")
main:    -> 0.0041s
main: -- column_exists?(:p_ci_builds, "commit_id_convert_to_bigint")
main:    -> 0.0023s
main: -- column_exists?(:p_ci_builds, "erased_by_id_convert_to_bigint")
main:    -> 0.0022s
main: -- column_exists?(:p_ci_builds, "project_id_convert_to_bigint")
main:    -> 0.0023s
main: -- column_exists?(:p_ci_builds, "runner_id_convert_to_bigint")
main:    -> 0.0021s
main: -- column_exists?(:p_ci_builds, "trigger_request_id_convert_to_bigint")
main:    -> 0.0021s
main: -- column_exists?(:p_ci_builds, "upstream_pipeline_id_convert_to_bigint")
main:    -> 0.0021s
main: -- column_exists?(:p_ci_builds, "user_id_convert_to_bigint")
main:    -> 0.0023s
main: -- quote_table_name(:p_ci_builds)
main:    -> 0.0000s
main: -- execute("LOCK TABLE ONLY \"p_ci_builds\" IN ACCESS EXCLUSIVE MODE")
main:    -> 0.0003s
main: -- quote_table_name(:p_ci_builds)
main:    -> 0.0000s
main: -- execute("LOCK TABLE \"p_ci_builds\" IN ACCESS EXCLUSIVE MODE")
main:    -> 0.0003s
main: -- remove_column(:p_ci_builds, "auto_canceled_by_id_convert_to_bigint", {:if_exists=>true})
main:    -> 0.0132s
main: -- remove_column(:p_ci_builds, "commit_id_convert_to_bigint", {:if_exists=>true})
main:    -> 0.0112s
main: -- remove_column(:p_ci_builds, "erased_by_id_convert_to_bigint", {:if_exists=>true})
main:    -> 0.0069s
main: -- remove_column(:p_ci_builds, "project_id_convert_to_bigint", {:if_exists=>true})
main:    -> 0.0067s
main: -- remove_column(:p_ci_builds, "runner_id_convert_to_bigint", {:if_exists=>true})
main:    -> 0.0091s
main: -- remove_column(:p_ci_builds, "trigger_request_id_convert_to_bigint", {:if_exists=>true})
main:    -> 0.0060s
main: -- remove_column(:p_ci_builds, "upstream_pipeline_id_convert_to_bigint", {:if_exists=>true})
main: == [advisory_lock_connection] object_id: 53240, pg_backend_pid: 577
STDERR:
---- End output of "bash"  ----
Ran "bash"  returned 1
Thank you for using GitLab Docker Image!
Current version: gitlab-ce=17.2.0-ce.0

**Comment by JonasSchubert** [comment]
Hi @socza I think you are referring to the Gitlab CE self hosted container?
There is already an active issue [there](https://gitlab.com/gitlab-org/gitlab/-/issues/473337) regarding db migrations. Might be your problem, too.
This is the repository for the gitlab plugin of semantic-release. 😉

**Comment by fgreinacher** [comment]
I'm closing this. Please reach out the GitLab team if needed.
