### ISSUE TITLE
Files uploaded using assets with default target project_upload are not downloadable using link created in release

### ISSUE THREAD

**Issue by aldenbe** [semantic-release/gitlab#753]
The link generated when publishing a release is in the format 

`https://gitlab.com/-/<project path>/uploads/<upload id>/<file>` however files are available at `https://gitlab.com/-/project/<project id>/uploads/<upload id>/<file>`

This causes links in releases to return 404

**Comment by JonasSchubert** [comment]
Hi @aldenbe and thanks for you issue and PR.
Can you provide a example repository or the settings this repository uses. Especially whether you configured a [repository](https://semantic-release.gitbook.io/semantic-release/usage/configuration#repositoryurl) in the `package.json`?
And also which Gitlab version and semantic release version (and plugin versions) you are using?

**Comment by aldenbe** [comment]
> Hi @aldenbe and thanks for you issue and PR. Can you provide a example repository or the settings this repository uses. Especially whether you configured a [repository](https://semantic-release.gitbook.io/semantic-release/usage/configuration#repositoryurl) in the `package.json`? And also which Gitlab version and semantic release version (and plugin versions) you are using?

The entirety of my current gitlab interactions are based around a private group with a lot of my environment tailored to interacting with that group specifically. It may not be as frustrating for me to demonstrate this publicly as I would guess, but it would take me a decent amount of time to be willing to find out.

Otherwise https://github.com/semantic-release/gitlab/issues/750#issuecomment-2250436652 seems to suggest others are experiencing the same result, and while https://docs.gitlab.com/ee/api/projects.html#markdown-uploads makes claims that in my testing appear to not be true, my solution does line up as valid given their documented api response.

**Comment by aldenbe** [comment]
Also, it might be worth updating the readme to mention that the default target (on gitlabs end too) of direct uploads is just all around terrible, and either the package registry or external file hosting should be used if possible.

**Comment by aodendaal** [comment]
I have a [public demo repo](https://gitlab.com/andre3254704/test-demo) you are welcome to use which I have for testing semantic release and which demonstrates the recent bug with the Changelog giving 404.

**Comment by fgreinacher** [comment]
> I have a [public demo repo](https://gitlab.com/andre3254704/test-demo) you are welcome to use which I have for testing semantic release and which demonstrates the recent bug with the Changelog giving 404.

Thank you @aodendaal :thum
