### ISSUE TITLE
Validation failed: Description can\'t be blank

### ISSUE THREAD

**Issue by gajus** [semantic-release/gitlab#76]
I am running:

```bash
docker run -e NPM_TOKEN=${NPM_TOKEN} -e GITLAB_TOKEN=${GITLAB_TOKEN} $CI_REGISTRY_IMAGE:$BUILD_TAG /bin/sh -c 'npm run build && semantic-release --no-ci'

```

and getting:

```
  body:
   { message: 'Validation failed: Description can\'t be blank' },
  pluginName: '@semantic-release/gitlab' }
{ HTTPError: Response code 400 (Bad Request)
    at EventEmitter.emitter.on (/srv/node_modules/got/source/as-promise.js:74:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)

```

It is not clear what description the error is referring to.

Here is an example of another (public) project getting the same error:

https://git.happy-dev.fr/startinblox/devops/siblab-js/-/jobs/5312

**Comment by pvdlg** [comment]
According to your configuration ([here](https://git.happy-dev.fr/startinblox/devops/siblab-js/blob/master/package.json#L17)) you are not using any plugin to generate the changelog.

It seems the GitLab API require a description when associating a release to a tag. This description is the release not which is generated by the `generateNotes` plugins.

Is it intentional to not have any `generateNotes` plugins?

**Comment by gajus** [comment]
I am not using any `generateNotes` plugins. Where is this requirement documented?

**Comment by pvdlg** [comment]
It's not documented as I didn't know GitLab required a description for the release.
What's the reason to not use a `generateNotes` plugin?

**Comment by gajus** [comment]
> What's the reason to not use a generateNotes plugin?

I don't know what `generateNotes` plugin is and why I should use it, other than what you just told me. Is there a documentation for how to install/ what it does?

**Comment by pvdlg** [comment]
https://github.com/semantic-release/semantic-release#release-steps

https://github.com/semantic-release/semantic-release/blob/master/docs/usage/plugins.md#plugins

https://github.com/semantic-release/release-notes-generator

**Comment by gajus** [comment]
Thank you – it works.

I would include this as a minimum-required configuration to the `@semantic-release/gitlab` README.md:

```json
"release": {
  "plugins": [
    "@semantic-release/release-notes-generator",
    [
      "@semantic-release/gitlab",
      {
        "gitlabUrl": "https://git.applaudience.com/"
      }
    ],
    "@semantic-release/npm"
  ]
},

```

and would also explain that the `@semantic-release/release-notes-generator` and `@semantic-release/npm` do not need to be installed separately, as per https://github.com/semantic-release/semantic-release/blob/master/docs/usage/plugins.md#plugins-installation.
