### ISSUE TITLE
add push via CI_JOB_TOKEN

### ISSUE THREAD

**Issue by pimperator** [semantic-release/gitlab#771]
Hi Guys, 
gitlab has recently enabled the ability to push via CI_JOB_TOKEN. Details see [here](https://docs.gitlab.com/ee/ci/jobs/ci_job_token.html#git-push-to-your-project-repository)
Still the feature needs to be enabled and is in development but it is just a matter of time when it is stable.

Since any other personal, group or project access token might be not immediately revoked when a teammember leaves the company going back to CI_JOB_TOKEN is more safe. Also it works out of the box since it is available anyways.

For compatibility reasons the status quo shall remain. It should be either GL_TOKEN or GITLAB_TOKEN  and if not defined CI_JOB_TOKEN.

**Comment by fgreinacher** [comment]
Thanks for reaching out. 

We already track this via https://github.com/semantic-release/gitlab/issues/156. 

Feel free to join the discussion there!
