### ISSUE TITLE
Allow send success comment on related issues

### ISSUE THREAD

**Issue by rollsover** [semantic-release/gitlab#779]
I dot use closes issues, but issue is closing after merge manually, so after release i want see in issue in witch release is feature resolved

I seen implementation, so we may get related issues by this [api](https://docs.gitlab.com/ee/api/merge_requests.html#list-issues-related-to-the-merge-request), and send comments like issues, but without filtering by status (with not closed issues)

Maybe use some alternative message, and by default is feature disabled by config

Or second way:

Get from project config, info about "closes" feature, and use related issues as alternative for closes issues

**Comment by JonasSchubert** [comment]
Hi @rollsover and sorry for the late response!
I hope I understand your request correct: You want to send a success comment only to a filtered list of issues?
You can do that if you are using version `13.2.0` and up. These versions have the possibility to set [conditions](https://github.com/semantic-release/gitlab?tab=readme-ov-file#successcommentcondition) for success comments.
If you only want to comment on issues which are closed, you could set the `successCommentCondition` to something like `"<% return issue.state === 'closed' %>"`.

**Comment by JonasSchubert** [comment]
@rollsover Do you still have some questions or did my answer help you?

**Comment by fgreinacher** [comment]
Closing this as the question is answered in my opinion.

Feel free to reopen if needed!
