### ISSUE TITLE
GitLab error 400 "released_at" is missing

### ISSUE THREAD

**Issue by Nargonath** [semantic-release/gitlab#80]
I supposed GitLab updated their API because it used to work and without us changing anything we get now a 400 HTTP status code error. This happens when trying to publish the tag in GitLab.

Here are some details that we get from GitLab in our CI:
`ERROR:  null value in column "released_at" violates not-null constraint`
`INSERT INTO "releases" ("tag", "description", "project_id", "created_at", "updated_at", "description_html", "cached_markdown_version", "author_id", "name", "sha")`.

I cannot send the values in itself as they contain information on a private project I'm working on. If needed I could give the values types.

I browsed their API documentation and I didn't notice this field. Does anyone encounter a similar issue?

**Comment by Nargonath** [comment]
One thing I can add is that the basic tag is created in GitLab but it errors when trying to add the detailed changelog to it.

**Comment by eugenechu** [comment]
Got similar error when using `@semantic-release/gitlab@3.1.2` and `@semantic-release/git@7.0.8` but with field tag desription.
`
Failed step "publish" of plugin "@semantic-release/gitlab"
An error occurred while running semantic-release: { HTTPError: Response code 400 (Bad Request)
...
 body: '{"tag_name":"v0.5.5","description":""}',
...
 body: { message: "Validation failed: Description can't be blank" },
 pluginName: '@semantic-release/gitlab' }error Command failed with exit code 1.
`

Seems like it may relate to [GitLab](
`https://gitlab.com/gitlab-org/gitlab-ce/commit/05b52e0f5e4d06edb736849daaac5c33c68c1d47#00eb19af35bffc05dd688e732df3f8aeaa5f547e_132_156`)

Is this a problem with version of `semantic-release` plugins or with changed `GitLab` API?

**Comment by pvdlg** [comment]
This plugin doesn't send `released_at` when calling the create release API.
However, according to the GitLab documentation (https://docs.gitlab.com/ee/api/releases/#create-a-release) the field `released_at` is not required.
So this seems to be a bug in GitLab. Could you open an issue with GitLab?

**Comment by Nargonath** [comment]
Thanks for the answer @pvdlg . I'll go create an issue and link it back here.

**Comment by Nargonath** [comment]
There seems to already have an opened issue on the matter, I just made a comment mentioning this issue: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/29577#note_203520370.

**Comment by pvdlg** [comment]
It seems it was merged. Can this issue be closed then?

**Comment by eugenechu** [comment]
I got this issue fixed with GitLab updated to 12.1 version + latest version of semantic-release(15.13.21 if I not mistaken).

**Comment by Nargonath** [comment]
Alright cool if this was fixed. Thanks for closing the issue.
