### ISSUE TITLE
GITLAB_URL & GITLAB_PREFIX can be replaced by CI_API_V4_URL and be optional  for any gitlab instance since 11.7

### ISSUE THREAD

**Issue by unlight** [semantic-release/gitlab#84]
GITLAB_URL & GITLAB_PREFIX can be replaced by CI_API_V4_URL and be optional  for any gitlab instance since 11.7

https://docs.gitlab.com/ee/ci/variables/predefined_variables.html

**Comment by pvdlg** [comment]
`GITLAB_URL` and `GITLAB_PREFIX` are semantic-release specific environment variables.

`CI_API_V4_URL` is an environment variable that is set by GitLab only when you use GitLab CI.

Those serve different purpose.

**Comment by unlight** [comment]
What I mean, that you can use it in code, e.g:
```
const apiUrl = process.env.CI_API_V4_URL || `${GITLAB_URL}${GITLAB_PREFIX} || other default`;
```

**Comment by thesmiley1** [comment]
I agree this makes sense.

Currently, the alternative is to create custom CI variables, which is repetitive and duplicative (being necessary for every project, and duplicating data that is already made available by the platform with a different variable name), or to pass a string programatically, which is brittle.

`semantic-release` users would want to override these defaults with familiar `*_URL` and `*_PREFIX` for consistency, sure, but the current approach is adding unneccessary indirection (in the case of wanting to use default values) and is more brittle than it needs to be with respect to setting up new projects on custom GitLab instances or moving a project between GitLab instances.
