### ISSUE TITLE
EMISSINGREPO thrown when in fact the reverse proxy in front of GitLab is incorrectly configured

### ISSUE THREAD

**Issue by esciara** [semantic-release/gitlab#99]
See toward the end of https://github.com/semantic-release/gitlab/issues/63#issuecomment-527080331.

Verification currently does not make a distinction when the repository is really missing (response with `statusCode` at `404` and `statusMessage` is `Project Not Found`) and when there is a problem with a badly configured reverse-proxy (same but `statusMessage` is `Not Found`).

**Comment by pvdlg** [comment]
See https://github.com/semantic-release/gitlab/pull/100#issuecomment-546760092
